install.packages("tidyverse")
install.packages("yaml")
install.packages("rmarkdown")
install.packages("janitor")
install.packages("naniar")
install.packages("pryr")
install.packages("tinytex")
install.packages("ggplot2")
install.packeges("plotly")

tinytex::install_tinytex() 